### ISSUE TITLE
crash when logging in to google

### ISSUE THREAD

**Issue by Chandz5995** [termux-user-repository/chromium-builder#33]
When I enter the Google login page, Chromium immediately crashes. over and over again, tried running chromium without xfce, same crash. even though the previous version, I don't know which version, it was all normal. is there a solution?

**Comment by jorbig** [comment]
This should be fixed tomorrow:
https://github.com/termux-user-repository/tur/issues/1182#issuecomment-2395087983

**Comment by Chandz5995** [comment]
Has it been fixed?

> This should be fixed tomorrow: [termux-user-repository/tur#1182 (comment)](https://github.com/termux-user-repository/tur/issues/1182#issuecomment-2395087983)

is it fixed now?

**Comment by licy183** [comment]
No. As Termux's builder has bumped to Ubuntu 24.04, it needs more time to workaround this change.

**Comment by Chandz5995** [comment]
> No. As Termux's builder has bumped to Ubuntu 24.04, it needs more time to workaround this change.

I don't understand why there were no problems before, and now there are problems like this? I think the problem comes from the Termux update?

**Comment by licy183** [comment]
As for this issue, Chromium will call the WebHID API when opening Google Login Pgae, and Chromium will call the HID Service. In the native Termux Chromium, since the support of udev is turned off, the initialization of HID Service will fail, resulting in null pointer (or DCHECK failure), so it cannot be used normally.

As for the build issue, it fails to build due to soversion mismatch. Chromium is cross-compiled. The triple of the host is x64_64-linux-gnu, and the triple of the target is aarch64-linux-android. Some programs are compile targeting the host triple to generate something the target needs, such as v8 snapshot. When executing the host build, the sysroot used is the debian bullseye provided by Google, and the soversion of libffi in it is 7. The current Termux CI uses Ubuntu 24.04, and the soversion in it is 8. The version mismatch causes the generator to fail to run.
